Repository cplusplus/draft, pull requests merged in 2019-11, with the labels that each got.

#3359 [range.join.iterator] Clarify if ... otherwise ladder.
  source/ranges.tex
Labels: nb-comment

#3361 [class.copy.assign] Remove semicolon in 'of the form' phrase.
  source/classes.tex
Labels: nb-comment

#3360 [basic.types]/2 replace macro constant with constexpr variable
  source/basic.tex
Labels: decision-required

#3390 [basic.lookup.argdep] Inline the definition of 'interface'.
  source/basic.tex
  source/modules.tex
Labels: nb-comment

#3472 Motions 2019 11 lwg 1: P1917R0 C++ Standard Library Issues to be moved in Belfast
  source/algorithms.tex
  source/concepts.tex
  source/containers.tex
  source/iostreams.tex
  source/iterators.tex
  source/ranges.tex
  source/support.tex
  source/time.tex
  source/utilities.tex
Labels: changes requested

#3493 [time.cal.wdidx.nonmembers] Remove extra "
  source/time.tex
Labels: tiny

#3469 [range.istream] Relocate under [range.factories]
  source/ranges.tex
Labels: after-motions

#2768 Lex.charset fixes
  source/lex.tex
Labels: needs rebase
