Repository cplusplus/draft, pull requests merged in 2019-09, with the labels that each got.

#3211 [span.syn] Fix inconsistent class key in tuple_size/tuple_element
  source/containers.tex
Labels: tiny

#3246 [index] Create first-letter subheadings for the general index.
  source/Makefile
  source/generalindex.ist
  source/latexmkrc
  source/libraryindex.ist
  source/macros.tex
Labels: decision-required

#3239 [std] Improve indexing of standard library headers.
  source/algorithms.tex
  source/atomics.tex
  source/back.tex
  source/basic.tex
  source/classes.tex
  source/compatibility.tex
  source/concepts.tex
  source/containers.tex
  source/declarations.tex
  source/diagnostics.tex
  source/expressions.tex
  source/future.tex
  source/iostreams.tex
  source/iterators.tex
  source/lib-intro.tex
  source/locales.tex
  source/macros.tex
  source/numerics.tex
  source/ranges.tex
  source/regex.tex
  source/strings.tex
  source/support.tex
  source/templates.tex
  source/threads.tex
  source/time.tex
  source/utilities.tex
Labels: big

#3159 [index] Add index of concept names.
  source/Makefile
  source/back.tex
  source/concepts.tex
  source/iterators.tex
  source/macros.tex
  source/ranges.tex
  source/std.tex
  source/support.tex
  source/threads.tex
  source/utilities.tex
Labels: big
