Repository cplusplus/draft, pull requests merged in 2020-09, with the labels that each got.

#4154 [macros] Fix PDF links to clauses and annexes
  source/macros.tex
Labels: nb-comment

#4151 [except.uncaught] Remove parentheses when not invoking a function
  source/exceptions.tex
Labels: nb-comment

#4169 Fix hanging paragraphs for C++20
  source/algorithms.tex
  source/atomics.tex
  source/basic.tex
  source/classes.tex
  source/compatibility.tex
  source/containers.tex
  source/declarations.tex
  source/diagnostics.tex
  source/exceptions.tex
  source/expressions.tex
  source/future.tex
  source/grammar.tex
  source/intro.tex
  source/iostreams.tex
  source/iterators.tex
  source/lib-intro.tex
  source/locales.tex
  source/numerics.tex
  source/overloading.tex
  source/preprocessor.tex
  source/ranges.tex
  source/regex.tex
  source/statements.tex
  source/strings.tex
  source/support.tex
  source/templates.tex
  source/threads.tex
  source/time.tex
  source/utilities.tex
  tools/fix-hanging.pl
Labels: nb-comment

#4175 [intro.ack] Dissolve subclause.
  source/back.tex
  source/intro.tex
  source/xrefdelta.tex
Labels: nb-comment

#4171 Adjust Foreword based on comments from ISO/CS
  source/preface.tex
Labels: nb-comment

#4140 [atomics.types.operations] Fix typo in exposition-only code
  source/atomics.tex
Labels: nb-comment

#4141 [util.smartptr.shared.cast] Add hyphen for 'well-formed'.
  source/utilities.tex
Labels: nb-comment

#4148 [variant.helper] Use 'struct' for variant_size and variant_alternative
  source/utilities.tex
Labels: nb-comment

#4149 [mem.res.syn] Add default template argument for polymorphic_allocator
  source/utilities.tex
Labels: nb-comment

#4150 [mem.poly.allocator.mem] Fix syntax for variadic template declaration
  source/utilities.tex
Labels: nb-comment

#4143 [defns.undefined] Move cross-reference to [expr.const]
  source/intro.tex
Labels: nb-comment

#4182 [intro.refs] Fix clause reference to ISO/IEC 9899.
  source/intro.tex
Labels: nb-comment

#4183 [intro.refs] Update from ISO/IEC 10646-1:1993 to ISO/IEC 10646:2003.
  source/future.tex
  source/intro.tex
Labels: nb-comment

#4187 [intro.defs] Refer to undated ISO/IEC 2382 for the terminology.
  source/intro.tex
Labels: nb-comment

#4188 [intro.refs,time.format] Fix normative references.
  source/back.tex
  source/basic.tex
  source/intro.tex
  source/time.tex
Labels: nb-comment

#4189 [intro.compliance.general] Properly reference normative clauses
  source/intro.tex
Labels: nb-comment

#4191 [intro.defs] Remove cross-references to main part
  source/intro.tex
Labels: nb-comment

#4198 [everywhere] Stop talking about C++ International Standards.
  source/compatibility.tex
  source/future.tex
  source/preprocessor.tex
  source/support.tex
  source/utilities.tex
Labels: ballot-comment

#4165 [std] Use \defnadj to improve/add many index entries.
  source/basic.tex
  source/classes.tex
  source/declarations.tex
  source/iostreams.tex
  source/lib-intro.tex
  source/templates.tex
  source/threads.tex
Labels: index

#4060 [iterator.cpp17] Index old-style iterator requirements.
  source/iterators.tex
Labels: index

#3984 [concepts.equality] Replace spurious 'this document'
  source/concepts.tex
Labels: changes requested
