Repository cplusplus/draft, pull requests merged in 2023-11, with the labels that each got.

#6639 [intro.refs] Move nicknames for standards to relevant subclauses
  source/intro.tex
  source/lib-intro.tex
  source/regex.tex
Labels: ballot-comment

#3906 Strike surviving mentions of "storage class" (outside of stable names and grammar)
  source/classes.tex
  source/declarations.tex
  source/overloading.tex
  source/templates.tex
Labels: needs rebase, changes requested

#6457 [intro.races] Remove unclear uses of "shall"
  source/basic.tex
Labels: needs rebase

#6613 [iterator.requirements.general] Clarify non-forward iterator
  source/iterators.tex
Labels: lwg

#6648 [diff.cpp23.library] Note new headers in C++26
  source/compatibility.tex
Labels: needs rebase
